import { TrainProfile as Train } from '@vicons/carbon'
import { PlaneDeparture as Plane, Car, Ship, Bus } from '@vicons/tabler'

export const travelCalendarActivities = [
  {
    content: '哈尔滨',
    // size: 'large',
    // timestamp: '2023-10-27 - 2023-10-29',
    // type: 'primary',
    // icon: Train,
    // color: '#0bbd87',
    food: [],
    scenicSpots: [],
    trafficNumber: [],
    // hollow: true,
  },
  {
    content: '延吉',
    // size: 'large',
    // timestamp: '2023-10-27 - 2023-10-29',
    // type: 'primary',
    // icon: Train,
    // color: '#0bbd87',
    food: [],
    scenicSpots: [],
    trafficNumber: [],
    // hollow: true,
  },
  {
    content: '青岛',
    // size: 'large',
    // timestamp: '2023-10-27 - 2023-10-29',
    // type: 'primary',
    // icon: Train,
    // color: '#0bbd87',
    food: [],
    scenicSpots: [],
    trafficNumber: [],
    // hollow: true,
  },
  {
    content: '郑州',
    // size: 'large',
    // timestamp: '2023-10-27 - 2023-10-29',
    // type: 'primary',
    // icon: Train,
    // color: '#0bbd87',
    food: [],
    scenicSpots: [],
    trafficNumber: [],
    // hollow: true,
  },
  {
    content: '马来西亚仙本那',
    // size: 'large',
    // timestamp: '2023-10-27 - 2023-10-29',
    // type: 'primary',
    // icon: Train,
    // color: '#0bbd87',
    food: [],
    scenicSpots: [],
    trafficNumber: [],
    // hollow: true,
  },
  {
    content: '美国拉斯维加斯',
    // size: 'large',
    // timestamp: '2023-10-27 - 2023-10-29',
    // type: 'primary',
    // icon: Train,
    // color: '#0bbd87',
    food: [],
    scenicSpots: [],
    trafficNumber: [],
    // hollow: true,
  },
  {
    content: '美国旧金山',
    // size: 'large',
    // timestamp: '2023-10-27 - 2023-10-29',
    // type: 'primary',
    // icon: Train,
    // color: '#0bbd87',
    food: [],
    scenicSpots: [],
    trafficNumber: [],
    // hollow: true,
  },
  {
    content: '美国洛杉矶',
    // size: 'large',
    // timestamp: '2023-10-27 - 2023-10-29',
    // type: 'primary',
    // icon: Train,
    // color: '#0bbd87',
    food: [],
    scenicSpots: [],
    trafficNumber: [],
    // hollow: true,
  },
  {
    content: '莆田',
    size: 'large',
    timestamp: '2026-02-21 - 2026-02-23',
    type: 'primary',
    icon: Train,
    poster: 'https://cdn.sanghangning.cn/ai-images/cnpt.png',
    color: '#0bbd87',
    food: [
      '吃席',
      '卤面',
      '炝肉',
      '炖罐'
    ],
    scenicSpots: [
      '东吴村',
      '湄洲岛'
    ],
    trafficNumber: [
      {
        number: 'G1673',
        time: '02.21 11:25 - 02.21 15:30',
        area: '台州 - 莆田',
      },
      {
        number: 'D3212',
        time: '02.23 18:17 - 02.23 22:52',
        area: '莆田 - 杭州东',
      },
    ],      // hollow: true,
  },
  {
    content: '马来西亚吉隆坡',
    size: 'large',
    timestamp: '0206-02-14 - 2026-02-16',
    type: 'primary',
    icon: Plane,
    color: '#0bbd87',
    poster: 'https://cdn.sanghangning.cn/ai-images/myjlp.png',
    food: [
      '海脚人',
      '榴莲：老树猫山王、黑刺、红肉、小甜甜',
      '肥肥蟹',
      ''
    ],
    scenicSpots: [
      '中央艺术坊',
      '独立广场',
      '双子塔'
    ],
    trafficNumber: [
      {
        number: '埃塞俄比亚航空ET638',
        time: '02.14 15:50 - 02.14 17:15',
        area: '新加坡樟宜机场 - 吉隆坡国际机场',
      },
      {
        number: '亚洲航空XD7302',
        time: '02.16 07:45 - 02.16 13:10',
        area: '吉隆坡国际机场 - 杭州萧山国际机场',
      }
    ],  
    // hollow: true,
  },
  {
    content: '新加坡',
    size: 'large',
    timestamp: '2026-02-11 - 2026-02-14',
    type: 'primary',
    icon: Plane,
    color: '#0bbd87',
    poster: 'https://cdn.sanghangning.cn/ai-images/singapore.png',
    food: [
      '亚坤',
      '松发肉骨茶',
      '友吉海南鸡饭',
      'Kiliney Kopitiam - Lucky Plaza',
      'Nasi Lemak Ayam Taliwang',
      'Muthu\'s Curry',
      '南南咖喱娘惹料理',
      ''
    ],
    scenicSpots: [
      '牛车水',
      '鱼尾狮公园',
      '克拉码头',
      '滨海湾花园',
      '花穹',
      '云雾林',
      '夜间动物园（Night Safiri）',
      '乌节路',
      'City Tours',
      '苏丹回教堂',
      '小印度',
      '星耀樟宜'
    ],
    trafficNumber: [
      {
        number: '春秋航空9C8549',
        time: '02.11 17:30 - 02.11 23:10',
        area: '上海浦东国际机场 - 新加坡樟宜机场',
      }
    ],      // hollow: true,
  },
    {
      content: '北京',
      size: 'large',
      timestamp: '2025-09-20 - 2025-09-21',
      type: 'primary',
      icon: Train,
      poster: 'https://cdn.sanghangning.cn/ai-images/cnbj2.png',
      food: [
        '南门涮肉(天坛总店)',
        '卤煮',
        '便宜坊烤鸭(和平里店)',
        '老北京冰棍',
      ],
      scenicSpots: ['天坛', '天安门广场', '鸟巢', '陶喆演唱会', '龚王府'],
      trafficNumber: [
        {
          number: 'G32',
          time: '09.20 07:47 - 09.20 12:20',
          area: '杭州东 - 北京南',
        },
        {
          number: 'G195',
          time: '09.21 04:17 - 09.2 22:20',
          area: '北京南 - 杭州东',
        },
      ],
    },
    {
      content: '温州',
      size: 'large',
      timestamp: '2025-09-14',
      type: 'primary',
      icon: Car,
      color: '#0bbd87',
      food: ['老温州·温州菜'],
      scenicSpots: ['五马街'],
      trafficNumber: [],
    },
    {
      content: '三亚',
      size: 'large',
      timestamp: '2025-09-06 - 2025-09-07',
      type: 'primary',
      icon: Train,
      color: '#0bbd87',
      poster: 'https://cdn.sanghangning.cn/ai-images/cnsy.png',
      food: ['岛上椰林·东方烤乳猪·海鲜餐厅', '糟粕醋火锅', '椰子饭'],
      scenicSpots: ['亚特兰蒂斯水世界', '亚特兰蒂斯水族馆'],
      trafficNumber: [
        {
          number: 'C7873',
          time: '09.06 09:17 - 09.06 09:50',
          area: '神州 - 亚龙湾',
        },
        {
          number: '首都航空JD5969',
          time: '09.07 22:50 - 09.08 01:00',
          area: '海口美兰国际机场 - 杭州萧山国际机场',
        },
      ],
    },
    {
      content: '万宁',
      size: 'large',
      timestamp: '2025-09-05',
      type: 'primary',
      icon: Plane,
      color: '#0bbd87',
      poster: 'https://cdn.sanghangning.cn/ai-images/cnwn.png',
      food: ['香草鸭', '海南粉'],
      scenicSpots: ['神州半岛', '石梅湾', '日月湾'],
      trafficNumber: [
        {
          number: '成都航空EU2264',
          time: '09.05 12:25 - 09.05 15:20',
          area: '杭州萧山国际机场 - 海口美兰国际机场',
        },
        {
          number: 'C7861',
          time: '09.05 16:32 - 09.05 17:36',
          area: '美兰 - 神州',
        },
      ],
    },
    {
      content: '日本横滨',
      size: 'large',
      timestamp: '2025-07-28',
      type: 'primary',
      icon: Train,
      color: '#0bbd87',
      poster: 'https://cdn.sanghangning.cn/ai-images/jphb.png',
      food: ['Yakiniku Watami（烧肉）'],
      scenicSpots: ['中华街', '红砖仓库', '空中缆车', '友都八喜', '爱电王'],
      trafficNumber: [
        {
          number: '[JK]根岸线',
          time: '07.28',
        },
      ],
    },
    {
      content: '日本镰仓',
      size: 'large',
      timestamp: '2025-07-28',
      type: 'primary',
      icon: Train,
      color: '#0bbd87',
      poster: 'https://cdn.sanghangning.cn/ai-images/jplc.png',
      food: ['海花亭（咖喱饭）'],
      scenicSpots: ['镰仓高校前站', '江之岛', '七里滨'],
      trafficNumber: [
        {
          number: '[JD]京滨急行线',
          time: '07.28',
        },
        {
          number: '[🚠]湘南单轨列车',
          time: '07.28',
        },
        {
          number: '[小绿车]江之岛电铁列',
          time: '07.28',
        },
      ],
    },
    {
      content: '日本富士山河口湖',
      size: 'large',
      timestamp: '2025-07-27',
      type: 'primary',
      icon: Train,
      color: '#0bbd87',
      poster: 'https://cdn.sanghangning.cn/ai-images/jpfss.png',
      food: ['猪排饭'],
      scenicSpots: ['河口湖', '富士急乐园（遇到了路演的女团）', '大石公园'],
      trafficNumber: [
        {
          number: '富士洄游号81',
          time: '07.27 09:02 - 07.25 11:21',
          area: '新宿 - 河口湖',
        },
        {
          number: '河口湖 RED LINE 旅游巴士',
          time: '07.27',
        },
        {
          number: '[🗻]富士急行线',
          time: '07.27',
        },
        {
          number: '[JC]中央线',
          time: '07.27',
        },
        {
          number: '[JK]京滨东北线',
          time: '07.27',
        },
      ],
    },
    {
      content: '日本埼玉县春日部',
      size: 'large',
      timestamp: '2025-07-26',
      type: 'primary',
      icon: Train,
      color: '#0bbd87',
      poster: 'https://cdn.sanghangning.cn/ai-images/jpcrb.png',
      food: [],
      scenicSpots: [
        '蜡笔小新胜地巡礼',
        '情报发信站',
        '乡土资料馆',
        'lala garden商场（遇到了路演的男团）',
        '风间家',
        '春日部市役所',
      ],
      trafficNumber: [
        {
          number: '[JJ]常磐线',
          time: '07.26',
        },
        {
          number: '[TS]东武晴空塔线',
          time: '07.26',
        },
      ],
    },
    {
      content: '日本东京',
      size: 'large',
      timestamp: '2025-07-25',
      type: 'primary',
      icon: Plane,
      color: '#0bbd87',
      poster: 'https://cdn.sanghangning.cn/ai-images/jpdj.png',
      food: [
        '一兰拉面',
        '各种711快餐',
        '駅弁车站便当',
        '烧鸟',
        'TsuruTonTan UDON NOODLE Brasserie SHIBUYA（乌冬面）',
        '神楽坂茶寮',
      ],
      scenicSpots: ['东京铁塔', '歌舞伎町', '涩谷sky', '浅草寺', '秋叶原'],
      trafficNumber: [
        {
          number: '春秋航空9C6131',
          time: '07.25 06:10 - 07.25 10:05',
          area: '上海浦东国际机场 - 东京成田机场',
        },
        {
          number: '春秋航空9C6998',
          time: '07.29 01:05 - 07.29 03:10',
          area: '东京羽田机场 - 上海浦东国际机场',
        },
        {
          number: '[E]大江户线',
          time: '07.25',
        },
        {
          number: '[JY]山手线',
          time: '07.25',
        },
        {
          number: '[A]浅草线',
          time: '07.26',
        },
        {
          number: '[G]银座线',
          time: '07.26',
        },
      ],
    },
    {
      content: '日本京都',
      size: 'large',
      timestamp: '2025-03-23',
      type: 'primary',
      icon: Train,
      color: '#0bbd87',
      poster: 'https://cdn.sanghangning.cn/ai-images/jpjd.png',
      food: [
        '本格炭火焼うなぎ えん 京都三条店（鳗鱼饭）',
        'Sumiyagura Kyoto（拉面）',
      ],
      scenicSpots: ['鸭川', '伏见稻荷大社', '清水寺', '三年坂二年坂'],
      trafficNumber: [
        {
          number: '坂急京都线',
          time: '2025-03-23 10:40 - 2025-03-23 12:13',
          area: '梅田 - 京都',
        },
      ],
      // hollow: true,
    },
    {
      content: '日本大阪',
      size: 'large',
      timestamp: '2025-03-21 - 2025-03-24',
      type: 'primary',
      icon: Plane,
      color: '#0bbd87',
      poster: 'https://cdn.sanghangning.cn/ai-images/jpdb.png',
      food: [
        '乌冬面（天下茶屋地铁站）',
        '章鱼小丸子（道顿堀）',
        '大興寿司（寿司）',
        '元祖炸串（炸串）',
        '环球影城路易斯纽约披萨饼屋',
        '环球影城奇诺比奥咖啡店',
        'Yakiniku Sukiyaki Jun（神户和牛）',
        '机场T2咖喱猪排饭与大阪烧',
      ],
      scenicSpots: [
        '心斋桥',
        '道顿堀',
        '通天阁',
        'USJ大阪环球影城',
        '梅田商圈',
        '天守城',
      ],
      trafficNumber: [
        {
          number: '春秋航空9C8589',
          time: '03.21 08:05 - 03.24 11:20',
          area: '上海浦东国际机场 - 大阪关西国际机场',
        },
        {
          number: '春秋航空9C6998',
          time: '03.24 19:30 - 03.24 21:20',
          area: '大阪关西国际机场 - 上海浦东国际机场',
        },
      ],
      // hollow: true,
    },
    {
      content: '香港',
      size: 'large',
      timestamp: '2025-02-03 - 2025-02-05',
      type: 'primary',
      icon: Train,
      color: '#0bbd87',
      poster: 'https://cdn.sanghangning.cn/ai-images/hk2.png',
      food: [
        '好盛冰室',
        '一乐烧鹅',
        '柠檬冰室',
        '迪士尼皇家宴会餐厅',
        '迪士尼火箭餐厅',
        '迪士尼冰条',
      ],
      scenicSpots: [
        'H2观光线',
        '铜锣湾',
        '星光大道',
        '维多利亚港',
        '中环',
        '香港迪士尼',
        '香港机场',
      ],
      trafficNumber: [
        {
          number: 'G5615 复兴号',
          time: '02.03 09:17 - 02.03 09:43',
          area: '深圳北 - 香港西九龙',
        },
        {
          number: '国泰航空CX962',
          time: '02.05 16:00 - 02.05 18:17',
          area: '香港国际机场 - 杭州萧山国际机场',
        },
      ],
      // hollow: true,
    },
    {
      content: '澳门',
      size: 'large',
      timestamp: '2025-02-02',
      type: 'primary',
      icon: Ship,
      poster: 'https://cdn.sanghangning.cn/ai-images/cnam2.png',
      food: ['牛杂', '咖喱鱼蛋', '兰香阁', '盈晖海鲜酒家', '安德鲁蛋挞'],
      scenicSpots: [
        '永利大皇宫',
        '伦敦人',
        '威尼斯人',
        '新葡京',
        '葡京',
        '美高梅',
        '美高梅美狮',
        '大三巴',
        '大炮台',
        '老永利发财树',
      ],
      // hollow: true,
      trafficNumber: [
        {
          number: '',
          time: '02.02 08:30 - 02.02 09:30',
          area: '深圳蛇口 - 澳门凼仔',
        },
        {
          number: '',
          time: '02.02 20:30 - 02.02 21:30',
          area: '澳门凼仔 - 深圳蛇口',
        },
      ],
      color: '#0bbd87',
    },
    {
      content: '泉州',
      size: 'large',
      timestamp: '2025-02-01',
      type: 'primary',
      icon: Train,
      color: '#0bbd87',
      poster: 'https://cdn.sanghangning.cn/ai-images/cnfjqz2.png',
      food: ['面线糊', '牛肉馆', '姜母鸭'],
      scenicSpots: ['开元寺', '钟楼', '天后宫'],
      trafficNumber: [
        {
          number: 'G1353',
          time: '01.31 15:55 - 01.31 16:07',
          area: '玉山南 - 上饶',
        },
        {
          number: 'G321',
          time: '01.31 16:36 - 01.31 18:21',
          area: '上饶 - 泉州',
        },
      ],
      // hollow: true,
    },
    {
      content: '景德镇',
      size: 'large',
      timestamp: '2024-11-07 - 2024-11-09',
      type: 'primary',
      icon: Bus,
      color: '#0bbd87',
      poster: 'https://cdn.sanghangning.cn/ai-images/cnjxjdz.png',
      food: ['回家吃饭', '小黄鱼', '欧记排挡', '兄弟记'],
      scenicSpots: ['陶溪川', '中国陶瓷博物馆','做陶瓷'],
      trafficNumber: [],
      // hollow: true,
    },
    {
      content: '贵州省',
      size: 'large',
      timestamp: '2024-10-01 - 2024-10-08',
      type: 'primary',
      poster: 'https://cdn.sanghangning.cn/ai-images/cngz.png',
      icon: Plane,
      color: '#0bbd87',
      food: [
        '羊肉粉',
        '牛肉粉',
        '烙锅',
        '丝娃娃',
        '牛瘪火锅',
        '酸汤鱼',
        '酸汤火锅',
        '1元猪肉串',
        '折耳根烤鱼',
        '香酥鸭',
        '火腿月饼',
        '爆炸土豆饼',
      ],
      scenicSpots: [
        '黔灵山',
        '夜郎谷',
        '千户苗寨',
        '小七孔',
        '黄果树大瀑布',
        '万峰顶',
        '织金洞',
        '织金大侠谷',
      ],
      trafficNumber: [
        {
          number: 'G1331',
          time: '10.01 15:06 - 10.01 22:40',
          area: '杭州东 - 贵阳北',
        },
        {
          number: '河北航空 NS3280',
          time: '10.08 07:55 - 10.08 10:10',
          area: '贵阳龙洞堡机场 - 杭州萧山国际机场',
        },
      ],
      // hollow: true,
    },
    {
      content: '济州岛',
      size: 'large',
      timestamp: '2024-07-27 - 2024-07-30',
      type: 'primary',
      icon: Plane,
      color: '#0bbd87',
      poster: 'https://cdn.sanghangning.cn/ai-images/krjzd.png',
      food: [
        '一品豆腐锅',
        '烤带鱼',
        '海女包饭',
        '紫菜包饭',
        '泡菜',
        '花生冰淇淋',
        'bhc炸鸡',
      ],
      scenicSpots: [
        '济州市区',
        '西归浦市',
        '柱状理节带',
        '偶来市场',
        '东门市场',
        '牛岛助力自行车/快艇',
        '咸德海滨浴场',
        '七星街',
        '免税店',
      ],
      trafficNumber: [
        {
          number: '长龙航空 GJ8940',
          time: '07.27 18:50 - 07.27 22:20',
          area: '杭州萧山国际机场 - 韩国济州岛国际机场',
        },
        {
          number: '春秋航空 9C8623',
          time: '07.30 22:35 - 07.30 23:05',
          area: '韩国济州岛国际机场 - 杭州萧山国际机场',
        },
      ],
      // hollow: true,
    },
    {
      content: '南昌',
      size: 'large',
      timestamp: '2024-03-23 - 2024-03-24',
      type: 'primary',
      poster: 'https://cdn.sanghangning.cn/ai-images/cnnc.png',
      icon: Train,
      color: '#0bbd87',
      food: [
        '白糖糕',
        '三杯鸡',
        '香辣鱼尾',
        '帝皇烤卤',
        '茼蒿炒腊肉',
        '黄豆鸡脚',
        '洪都大拇指',
        '瓦罐汤',
        '拌粉',
        '炒粉',
      ],
      scenicSpots: ['滕王阁', '江西博物馆', '八一广场', '万寿宫'],
      trafficNumber: [
        {
          number: 'G1641',
          time: '03.23 08:06 - 03.23 11:00',
          area: '杭州东 - 南昌西',
        },
      ],
      // hollow: true,
    },
    {
      content: '临海/仙居',
      size: 'large',
      timestamp: '2024-01-13 - 2024-01-14',
      type: 'primary',
      icon: Car,
      color: '#0bbd87',
      food: ['蛋清羊尾', '海苔饼', '荣小馆', '轰炸大鱿鱼', '乌饭麻糍'],
      scenicSpots: ['紫阳街', '神仙居'],
      trafficNumber: [],
      // hollow: true,
    },
    {
      content: '苏州',
      size: 'large',
      timestamp: '2023-12-30',
      type: 'primary',
      icon: Car,
      poster: 'https://cdn.sanghangning.cn/ai-images/cnjssz.png',
      color: '#0bbd87',
      food: ['苏城家宴', '醉蟹', '狮子头', '烧汁茄子', '烤鸭', '熏鱼'],
      scenicSpots: ['拙政园', '狮子林', '平江路', '平江路摇橹船'],
      trafficNumber: [],
      // hollow: true,
    },
    {
      content: '湖州',
      size: 'large',
      timestamp: '2023-12-17',
      type: 'primary',
      icon: Car,
      color: '#0bbd87',
      food: ['羊肉面', '周生记鸡爪'],
      scenicSpots: ['莫干山', '状元街', '小西街', '衣裳街'],
      trafficNumber: [],
      // hollow: true,
    },
    {
      content: '福州',
      size: 'large',
      timestamp: '2023-10-27 - 2023-10-29',
      type: 'primary',
      icon: Train,
      poster: 'https://cdn.sanghangning.cn/ai-images/cnfz.png',
      color: '#0bbd87',
      food: [
        '鱼丸',
        '肉片',
        '福屿伟榕捞化',
        '朱富贵海鲜火锅',
        '花生汤',
        '花生浆',
        '锅边糊',
      ],
      scenicSpots: ['福州国家森林公园', '三坊七巷'],
      trafficNumber: [
        {
          number: 'G1641',
          time: '10.27 19:03 - 10.27 22:49',
          area: '杭州南 - 福州',
        },
      ],
      // hollow: true,
    },
    {
      content: '香港',
      size: 'large',
      timestamp: '2023-10-08 - 2023-10-09',
      type: 'primary',
      icon: Train,
      color: '#0bbd87',
      poster: 'https://cdn.sanghangning.cn/ai-images/hk1.png',
      food: ['九龙冰室', '叉烧包'],
      scenicSpots: ['H1观光线', '铜锣湾', '星光大道', '维多利亚港'],
      trafficNumber: [
        {
          number: 'G5639 动感号',
          time: '10.8 09:33 - 10.8 09:52',
          area: '深圳北 - 香港西九龙',
        },
      ],
      // hollow: true,
    },
    {
      content: '澳门',
      size: 'large',
      timestamp: '2023-10-07',
      type: 'primary',
      icon: Ship,
      poster: 'https://cdn.sanghangning.cn/ai-images/cnam.png',
      food: ['招牌蒲国鸡饭', '柠檬车露雪糕', '安德鲁蛋挞', '旺记咖啡奶茶'],
      scenicSpots: [
        '永利大皇宫',
        '伦敦人',
        '威尼斯人',
        '新葡京',
        '老普京',
        '议事厅前地广场',
        '玫瑰圣母堂',
        '关前老街',
        '大三巴',
        '大炮台',
        '疯堂斜巷',
        '老永利发财树',
        '官也街',
        '银河综合度假城',
      ],
      // hollow: true,
      trafficNumber: [
        {
          number: '迅隆7',
          time: '10.7 08:00 - 10.7 09:00',
          area: '深圳蛇口 - 澳门凼仔',
        },
      ],
      color: '#0bbd87',
    },
    {
      content: '深圳',
      size: 'large',
      timestamp: '2023-10-06',
      type: 'primary',
      icon: Train,
      food: ['叉烧包', '猪脚饭', '粥底火锅'],
      scenicSpots: ['盐田坐车游', '中英街', '深圳湾公园'],
      // hollow: true,
      trafficNumber: [
        {
          number: 'G6004',
          time: '10.6 06:51 - 10.6 09:02',
          area: '汕头 - 深圳北',
        },
      ],
      color: '#0bbd87',
    },
    {
      content: '潮汕地区',
      size: 'large',
      timestamp: '2023-10-03 - 2023-10-05',
      type: 'primary',
      poster: 'https://cdn.sanghangning.cn/ai-images/cncs.png',
      icon: Train,
      trafficNumber: [
        {
          number: 'D7165',
          time: '10.3 20:10 - 10.3 23:16',
          area: '广州东 - 潮汕',
        },
        {
          number: 'D7157',
          time: '10.5 12:21 - 10.5 12:50',
          area: '潮汕 - 汕头',
        },
      ],
      // hollow: true,
      food: [
        '潮汕牛肉火锅',
        '生腌',
        '杏仁茶',
        '芝麻茶',
        '腐乳鸡翅',
        '猪脚圈',
        '生腌',
        '牛肉炒粿条',
        '粿条汤',
        '卤鹅',
        '反沙',
        '油柑汁',
        '甘蔗汁',
        '天地壹号',
        '无米粿',
        '咸水粿',
        '笋粿',
        '水晶球',
        '芋泥粿',
        '沙茶粿',
        '红桃粿',
        '薯粿',
        '鼠壳粿',
        '萝卜粿',
        '黄豆粿',
        '鲎粿',
        '粽球',
        '龟苓膏',
        '白粥',
      ],
      scenicSpots: ['潮州石牌坊', '潮州广济桥', '汕头小公园'],
      color: '#0bbd87',
      // https://zhuanlan.zhihu.com/p/51906896
    },
    {
      content: '广州',
      size: 'large',
      timestamp: '2023-10-02',
      type: 'primary',
      icon: Plane,
      poster: 'https://cdn.sanghangning.cn/ai-images/cngdgz.png',
      food: [
        '早茶（陶陶居）',
        '粤菜（小荔园）',
        '顺德菜（大榕树下）',
        '西士多',
        '牛杂',
        '奶茶',
        '咖喱鱼蛋',
        '烤乳鸽',
        '煲仔饭',
        '烧鸭',
        '养生汤',
        '鱼皮',
        '肠粉',
        '红米肠',
        '大油条配粥',
        '双皮奶',
        '叉烧包',
        '凤爪',
        '蒸排骨',
        '干炒牛河',
        '黑叉烧',
        '白切鸡',
      ],
      scenicSpots: ['夜游珠江', '城中村', '广州塔', '海心桥', '广东省博物馆'],
      // hollow: true,
      trafficNumber: [
        {
          number: 'CZ3522(波音787)',
          time: '10.2 11:35 - 10.2 13:40',
          area: '杭州萧山 - 广州白云',
        },
      ],
      color: '#0bbd87',
    },
    {
      content: '常州',
      size: 'large',
      timestamp: '2023-09-30',
      type: 'primary',
      food: ['卜記家常菜(土城路店)'],
      scenicSpots: ['太湖音乐节', '灵山大佛'],
      icon: Car,
      color: '#0bbd87',
      // hollow: true,
    },
    // {
    //   content: '宣城',
    //   size: 'normal',
    //   timestamp: '2023-09',
    //   type: 'warning',
    //   // icon: Car,
    //   hollow: true,
    // },
    {
      content: '嘉兴',
      scenicSpots: ['海宁盐官观潮公园'],
      food: ['肉粽', '嘉兴冷饮'],
      size: 'large',
      timestamp: '2023-08-05',
      type: 'primary',
      icon: Car,
      color: '#0bbd87',
    },
    {
      content: '武汉',
      scenicSpots: ['黄鹤楼'],
      food: ['牛肉粉', '藕汤'],
      size: 'large',
      timestamp: '2023-07-21 20:15 - 2023-07-22',
      type: 'primary',
      icon: Train,
      color: '#0bbd87',
    },
    {
      content: '宜昌',
      scenicSpots: ['两坝一峡游船', '三峡大坝'],
      food: ['凉虾', '奶汤肥鱼', '矮子馅饼'],
      size: 'large',
      timestamp: '2023-07-21 04:56 - 2023-07-21 07:07',
      type: 'primary',
      poster: 'https://cdn.sanghangning.cn/ai-images/cnhbyc.png',
      icon: Train,
      color: '#0bbd87',
    },
    {
      content: '武汉',
      scenicSpots: [
        '江汉路步行街',
        '汉口江滩',
        '长江轮渡',
        '武汉长江大桥',
        '户部巷',
        '夜游长江游船',
      ],
      food: ['热干面', '豆皮', '茶颜悦色', '周黑鸭'],
      size: 'large',
      timestamp: '2023-07-20 10:10 - 2023-07-20 14:43',
      type: 'primary',
      icon: Train,
      color: '#0bbd87',
    },
    {
      content: '扬州',
      scenicSpots: ['澡堂', '瘦西湖', '中国大运河博物馆', '搓脚'],
      food: ['扬州炒饭', '大煮干丝', '扬大酸奶'],
      size: 'large',
      timestamp: '2023-05-02 - 2023-05-03',
      type: 'primary',
      poster: 'https://cdn.sanghangning.cn/ai-images/cnjsyz.png',
      icon: Car,
      color: '#0bbd87',
    },
    {
      content: '溧阳',
      scenicSpots: ['南山竹海', '溧阳一号公路'],
      size: 'large',
      timestamp: '2023-05-02',
      type: 'primary',
      icon: Car,
      color: '#0bbd87',
    },
    {
      content: '泰国芭提雅',
      size: 'large',
      timestamp: '2019',
      type: 'primary',
      icon: Car,
      color: '#0bbd87',
      poster: 'https://cdn.sanghangning.cn/ai-images/thbty.png',
      food: ['芒果糯米饭','海鲜大餐'],
      scenicSpots: ['芭提雅海滩','东方公主号人妖秀','海上拖伞','芭提雅红灯区','芭提雅大象村'],
      trafficNumber: [
      ],
    },
    {
      content: '泰国曼谷',
      size: 'large',
      timestamp: '2019',
      type: 'primary',
      icon: Plane,
      color: '#0bbd87',
      poster: 'https://cdn.sanghangning.cn/ai-images/thmg.png',
      food: ['冬阴功汤','泰国炸鸡','泰国菜','泰国方便面'],
      scenicSpots: ['大皇宫','玉佛寺','湄南河','郑王庙','四面佛'],
      trafficNumber: [
      ],
    },
    {
      content: '越南胡志明市',
      size: 'large',
      timestamp: '2019',
      type: 'primary',
      icon: Plane,
      color: '#0bbd87',
      poster: 'https://cdn.sanghangning.cn/ai-images/vnhzm.png',
      food: ['麦当劳','越南河粉','咖啡'],
      scenicSpots: ['西贡中心邮局','胡志明咖啡公寓','胡志明市美术馆'],
      trafficNumber: [
      ],
    },
    {
      content: '越南岘港市',
      size: 'large',
      timestamp: '2019',
      type: 'primary',
      icon: Plane,
      color: '#0bbd87',
      poster: 'https://cdn.sanghangning.cn/ai-images/vnxg.png',
      food: ['越南春卷','越南河粉','烤鸡爪'],
      scenicSpots: ['巴拿山','岘港美溪沙滩','岘港夜市','岘港粉红大教堂','岘港龙桥'],
      trafficNumber: [
      ],
    },
    {
      content: '越南河内市',
      size: 'large',
      timestamp: '2019',
      type: 'primary',
      icon: Train,
      color: '#0bbd87',
      poster: 'https://cdn.sanghangning.cn/ai-images/vnhn.png',
      food: ['越南河粉','越南法棍','越南咖啡'],
      scenicSpots: ['36行古街','还剑湖','越南胡志明主席陵墓','文庙'],
      trafficNumber: [
      ],
    },
    {
      content: '待补充...',
      size: 'normal',
    },
]
